Fixed mismatch in printf types
espressif/esp-idf pull request #10304
Opened 2022-12-03 16:52 UTC by gregjesl

Closes #10303

2022-12-03 18:14 UTC, KaeLL commented
I believe the `<inttypes.h>` formats would be better.

2022-12-03 20:17 UTC, gregjesl commented
@KaeLL Updates made 👍

2022-12-04 10:14 UTC, igrr requested changes
Thanks for the PR @gregjesl!

Could you please also remove the following line in the same PR:
https://github.com/espressif/esp-idf/blob/7869f4e151e3ea2a308b991fbb8e9baa4cec313c/examples/get-started/hello_world/main/CMakeLists.txt#L4
and combine your changes into a single commit (using `git rebase -i`).

2022-12-04 10:14 UTC, igrr commented on examples/get-started/hello_world/main/hello_world_main.c
> +    printf("%luMB %s flash\n", flash_size / (uint32_t)(1024 * 1024),
```suggestion
    printf("%" PRIu32 "MB %s flash\n", flash_size / (uint32_t)(1024 * 1024),
```
(plus `#include <inttypes.h>` at the top of the file)

2022-12-04 14:28 UTC, gregjesl commented
@igrr Changes made. I updated a couple other print statements as well, let me know if I over-did it 😄

2022-12-05 14:53 UTC, igrr approved these changes

2022-12-05 14:54 UTC, igrr commented
sha=58d64f9a00dea44273004cfecc15f68008571ab3

2022-12-06 14:03 UTC, igrr commented
> I updated a couple other print statements as well, let me know if I over-did it 😄

@gregjesl I actually had to revert the changes related to 8- and 16-bit types. This is because newlib-nano (CONFIG_NEWLIB_NANO_FORMAT option) doesn't support 8-bit-specific format specifier produced by PRIu8... (Our internal CI have caught this issue on C2, where CONFIG_NEWLIB_NANO_FORMAT is enabled by default and this example has started failing.)

2022-12-13 07:45 UTC, merged