Nimble: Added Walkthrough tutorial for phy_prph example. (IDFGH-9693)
espressif/esp-idf pull request #11034
Opened 2023-03-21 10:44 UTC by ESPAbhinav

2023-03-21 11:10 UTC, rahult-github requested changes

2023-03-21 11:10 UTC, rahult-github commented on examples/bluetooth/nimble/ble_phy/phy_prph/tutorial/Ble_Phy_Peripheral_Example_Walkthrough.md
> +In this tutorial, the ble_phy peripheral example code for the espressif chipsets with BLE5.0 support is reviewed. This example aims at understanding how to establish connections on preferred PHY and
"This example aims at understanding how to establish connections on preferred PHY and changing LE PHY once the connection is established"

To 

"This example aims at understanding how to accept incoming connections on preferred PHY and process the request to change LE PHY once the connection is established"

2023-03-21 11:10 UTC, rahult-github commented on examples/bluetooth/nimble/ble_phy/phy_prph/tutorial/Ble_Phy_Peripheral_Example_Walkthrough.md
> +The main function calls `ble_svc_gap_device_name_set()` to set the default device name. 'blecent_phy' is passed as the default device name to this function.
change "blecent_phy"  to "bleprph-phy"

2023-03-21 11:10 UTC, rahult-github commented on examples/bluetooth/nimble/ble_phy/phy_prph/tutorial/Ble_Phy_Peripheral_Example_Walkthrough.md
> +To support increased messaging, BLE5.0 is added with extended advertising PDUs. These PDUs are broadcast-only events (like electronic beacons). The following function is used to make extended adverti
Bluetooth 4 --> Bluetooth 4.0

2023-03-21 11:10 UTC, rahult-github commented on examples/bluetooth/nimble/ble_phy/phy_prph/tutorial/Ble_Phy_Peripheral_Example_Walkthrough.md
> +static void
This section can be removed. Just keep ext_bleprph_advertise.

2023-03-21 11:10 UTC, rahult-github commented on examples/bluetooth/nimble/ble_phy/phy_prph/tutorial/Ble_Phy_Peripheral_Example_Walkthrough.md
> +
Add a line describing, that as s_current_phy value keeps changing , the advertising data also gets modified.

2023-03-24 04:48 UTC, rahult-github commented
sha=55fd7d43c1995ff2351da51aaaa4f2df6f71de2a

2023-03-24 11:39 UTC, rahult-github commented
sha=f9a895c9a80a83be0e17557b77b1403b47021bd7

2023-04-20 06:34 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/espressif/esp-idf?pullRequest=11034) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/espressif/esp-idf?pullRequest=11034) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/espressif/esp-idf?pullRequest=11034) it.</sub>

2024-02-19 07:27 UTC, Alvin1Zhang commented
Thanks for contribution again, sorry for very slow turnaround, changes have been merged with https://github.com/espressif/esp-idf/commit/6e1d60ea4830f4eb7bbb2bb01541cf1d45443931.

2024-02-19 07:27 UTC, closed without merging