docs: fix invalid reference to chip revision
espressif/esp-idf pull request #11743
Opened 2023-06-26 07:50 UTC by crespum

According to the [official errata document for the ESP32-C3](https://www.espressif.com/sites/default/files/documentation/esp32-c3_errata_en.pdf), revisions are named 0.1, 0.2 and so on (instead of 1, 2...).

2023-06-26 07:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/espressif/esp-idf?pullRequest=11743) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/espressif/esp-idf?pullRequest=11743) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/espressif/esp-idf?pullRequest=11743) it.</sub>

2023-06-27 06:08 UTC, krzychb requested changes
Hi @crespum, I left one comment.  

Thank you for spotting and correcting this issue!

2023-06-27 06:08 UTC, krzychb commented on docs/en/api-guides/jtag-debugging/index.rst
> +        Debugging through the USB interface implemented in {IDF_TARGET_NAME} requires to have a chip with revision 0.3 or newer. Please use other debugging options (e.g. with ESP-Prog) for chip revis
```suggestion
        Debugging through the USB interface implemented in {IDF_TARGET_NAME} requires to have a chip with revision 0.3 or newer. Please use other debugging options (e.g. with ESP-Prog) for chip revisions 0.1 and 0.2. The easiest way to determine the chip revision is to look for the ``boot: chip revision: v0.3`` message at the beginning of the boot log. See `SoC errata <https://www.espressif.com/sites/default/files/documentation/esp32-c3_errata_en.pdf>`_ for more details.
```

2023-06-27 06:55 UTC, crespum commented on docs/en/api-guides/jtag-debugging/index.rst
> +        Debugging through the USB interface implemented in {IDF_TARGET_NAME} requires to have a chip with revision 0.3 or newer. Please use other debugging options (e.g. with ESP-Prog) for chip revis
Good point.

2023-07-20 02:54 UTC, krzychb commented
Merged in https://github.com/espressif/esp-idf/commit/9cab62e734acc1446438e11a258cdbb756b320d5

2023-07-20 02:54 UTC, closed without merging