This enables project(... VERSION x.y.z.a ...) and DESCRIPTION etc.. usage
espressif/esp-idf pull request #12461
Opened 2023-10-25 12:17 UTC by kohait00

the current implementation of project.cmake
overrides the 

project() 

function with a macro which then calls the overridden function, but only provides the project name along with some predefined LANGUAGES..
in case someone wanted to specify additional LANGUAGES, DESCRIPTION etc... this is entirely ignored.
probably to keep things simple.

this fix enables the usage of all the parameters for project() including LANGUAGES

it splits the provided ARGV when there is LANGUAGES present, and eliminates the predefined languages that the project.cmake already wants to specify itself.

everything else is untouched.

this also has the benefit that the cmake own PROJECT_VERSION now is able to be specified via the project(VERSION x.y.z.a ...) and then can be used to initalize the PROJECT_VER, no need to specify the PROJECT_VER explicitly as a set(PROJECT_VER x.y.z.a)..

I admit that the solution is probly not optimal, feel free to improve on it.

2023-10-25 13:05 UTC, igrr requested changes
Thanks for the nice improvement @kohait00!

The code looks good to me overall, I have left a few cosmetic comments. My main concern is that the part about `LANGUAGES` seems to be a piece of fairly complex string/list manipulation code. I think we need to have some test coverage for it to prevent regressions.

Do you think you can add a few test cases to validate the behavior of this code?

I see we have two test cases for the version related logic,

https://github.com/espressif/esp-idf/blob/b4268c874a4cf8fcf7c0c4153cffb76ad2ddda4e/tools/test_build_system/test_git.py#L28

and, somewhat badly named,
https://github.com/espressif/esp-idf/blob/b4268c874a4cf8fcf7c0c4153cffb76ad2ddda4e/tools/test_build_system/test_kconfig.py#L129

Probably it makes sense to
- create a new test file, test_versions.py
- move the two existing tests there
- add one new test case about version from `project` call
- add another new test case (there or in another file) to validate the logic related to `LANGUAGE` argument handling

If you don't have time to work on adding test cases, please let us know anyway.

2023-10-25 16:05 UTC, kohait00 commented on tools/cmake/project.cmake
> +        # LANGUAGES definition from top level CMakeFile.txt exists
I refer to the main CMakeFile.txt of the project that contains the project() entry
* main CMakeFile.txt ?
* project CMakeFile.txt?
* anything you find best describing it..

2023-10-25 16:06 UTC, kohait00 commented on tools/cmake/project.cmake
> +    set(LANGUAGES_POS -1)
valid, will do

2023-10-25 16:08 UTC, kohait00 commented on tools/cmake/project.cmake
> +        # no LANGUAGES definition from top CMakeFile.txt
yeah, still learning CMake :)

2023-10-25 16:19 UTC, kohait00 commented
regarding the oetending of test cases that @igrr suggested, I could try but to be honest, I am a newby in python, barely read it.. It would take some time for sure.. But then again, I am also learning CMake now..

Probably easier for me would be to provide some project(xxx) string that can be used as a starting point..

My suggestion:
I provide review changes ASAP, including ducumentation and the test case ideas for VERSION, LANGUAGES etc
Then depending on the time frame that you guys have we can decide who would write the unit tests

2023-10-25 18:44 UTC, kohait00 commented
the promised test cases:

syntax reference
https://cmake.org/cmake/help/latest/command/project.html

# usual simple case may not break. Nothing more than that was possible before
project(hello_world)

# this should be possible but wont work, due to project.cmake internal LANGUAGES definition
project(hello_world CSharp C CXX ASM)

# bit more sophisticated with version, probably the future default
project(hello_world VERSION 2.4.3)

#even more complicated, order as in CMake documentation
project(hello_world VERSION 2.4.3 DESCRIPTION "Cool New Project" LANGUAGES C CXX ASM)

#order reversed, also in the languages definitions
project(hello_world VERSION 2.4.3.6 LANGUAGES CXX C ASM DESCRIPTION "Cool New Project" )

# to trigger the special case of C at the end
project(hello_world VERSION 2.4.3 DESCRIPTION "Cool New Project" LANGUAGES CXX ASM C )

# adding more to languages
project(hello_world VERSION 2.4.3 DESCRIPTION "Cool New Project" LANGUAGES CSharp C CXX ASM )

# duplicates
project(hello_world VERSION 2.4.3 DESCRIPTION "Cool New Project" LANGUAGES CSharp C CXX ASM C )

# full blown, strict docu conform order
project(hello_world VERSION 2.4.3 DESCRIPTION "Cool New Project" LANGUAGES CSharp C CXX ASM HOMEPAGE_URL "http://www.hello-world.com")

# full blown, arbitrary order
project(hello_world DESCRIPTION "Cool New Project" VERSION 2.4.3.6 LANGUAGES CSharp C CXX ASM HOMEPAGE_URL "http://www.hello-world.com")

# this schows that not all cases are caught, description will result in 'Cool new Project', the C at the end is gone
project(hello_world VERSION 2.4.3.6 LANGUAGES CXX C ASM DESCRIPTION "Cool New ProjectC" )

# this wont ever work,
project(hello_world VERSION 2.4.3 DESCRIPTION "Cool New Project" CSharp C CXX ASM C )

2023-10-25 19:21 UTC, igrr commented on tools/cmake/project.cmake
> +        # LANGUAGES definition from top level CMakeFile.txt exists
"top level CMakeLists.txt" is okay, you just have "CMakeFile.txt" written instead.

2023-10-25 20:06 UTC, kohait00 commented on tools/cmake/project.cmake
> +            set(PROJECT_VER ${PROJECT_VERSION})
added documentation

2023-10-25 20:07 UTC, kohait00 commented on tools/cmake/project.cmake
> +        # ARGV_SUB is "LANGUAGES X Y Z and the rest", just remove what we specify
i discribed it differntly, now it hopefully more clear what happens

2023-10-25 20:08 UTC, kohait00 commented on tools/cmake/project.cmake
> +        # so remove the definit option (;C; covers most, ;C at the end covers a special case.
removed in the following commits

2023-10-25 20:11 UTC, kohait00 commented on tools/cmake/project.cmake
> +        # ;C theoretically could be a DESCRITION or the like too, but unlikly
corrected

2023-10-25 20:17 UTC, kohait00 commented
I had to force push because I forgot to correct the 'unlikly' and fixed it via amend..

so that's the only change there.. 
I did an amend on f0d8b3f (which I have seen you  already cleared) and cherry pick on the documentation commit.. sorry for the hassle

there are no other changes so far

2023-11-23 13:39 UTC, sudeep-mohanty commented
@kohait00 Thanks for the suggestions and apologies for getting back to you late on this. I would be pulling in your changes but we might have to enable each `project()` argument gradually with some unit-tests for sanity so that we do not introduce any regression or breaking changes.

2023-11-23 13:47 UTC, sudeep-mohanty commented
sha=db01a1219fac2db85563a8baf388cb50c2136073

2023-11-23 14:28 UTC, sudeep-mohanty commented
sha=96e2a8a51c7c9613d0699e46e00c4ca160b5eace

2023-11-23 22:16 UTC, kohait00 commented
> @kohait00 Thanks for the suggestions and apologies for getting back to you late on this. I would be pulling in your changes but we might have to enable each `project()` argument gradually with some unit-tests for sanity so that we do not introduce any regression or breaking changes. Therefore, I would incorporate the addition of the `VERSION` argument first and then investigate the others subsequently.

I dont mind at all.. Do whatever is desired, since I currently can't provide additional testcases apart from what I tested locally.
If there is anything else I can do here to support, let me know..
Have fun.

2024-02-19 07:10 UTC, Alvin1Zhang commented
Thanks for contribution again, changes have been merged with https://github.com/espressif/esp-idf/commit/9beda4ce480de087b29df8750db38455d1de8f51.

2024-02-19 07:10 UTC, closed without merging