[SECURITY] [docs] Add warning about integrity of pre_encrypted_ota
espressif/esp-idf pull request #13132
Opened 2024-02-07 16:55 UTC by redfast00

Using the Encrypted Binary OTA provides confidentiality of the firmware, but does not provide integrity of the firmware: if an attacker is able to read out the firmware of one device (for example, via a fault-injection attack), they can also construct arbitrary valid encrypted OTA updates, that can then be installed on other devices that share the same private key.

This was not immediately obvious to me when I read what the pre_encrypted_ota functionality does, but became clear when I reviewed the cryptography used.

2024-02-07 16:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/espressif/esp-idf?pullRequest=13132) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/espressif/esp-idf?pullRequest=13132) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/espressif/esp-idf?pullRequest=13132) it.</sub>

2024-02-23 06:33 UTC, mahavirj commented
@redfast00 

> Using the Encrypted Binary OTA provides confidentiality of the firmware, but does not provide integrity of the firmware:

Do you mean authenticity of the firmware here? Because for integrity part, we already have several checks enabled during boot-up and OTA update stage.

> if an attacker is able to read out the firmware of one device (for example, via a fault-injection attack), they can also construct arbitrary valid encrypted OTA updates, that can then be installed on other devices that share the same private key.

It is recommended in the example README to protect the pre-encrypted OTA specific private key on the device. So I am not sure if I quite understand this point here, could you please elaborate? 

> This was not immediately obvious to me when I read what the pre_encrypted_ota functionality does, but became clear when I reviewed the cryptography used.

Secure boot and pre-encrypted OTA are 2 different features serving their own purposes. Ideally, we recommend that users refer to overall [security guide](https://docs.espressif.com/projects/esp-idf/en/latest/esp32c3/security/security.html) while deciding the features that best suit their use-cases.

2024-02-27 11:47 UTC, redfast00 commented
@mahavirj I indeed mean the authenticity (as in, 'can an attacker create a modified firmware update file that seems valid').

It is indeed recommended to protect the private key using Flash Encryption. However, on (I think currently all?) ESP32 chips, this flash encryption can be broken with fault injection attacks (see https://www.espressif.com/sites/default/files/advisory_downloads/AR2022-003%20Security%20Advisory%20Concerning%20Breaking%20the%20Hardware%20AES%20Core%20and%20Firmware%20Encryption%20of%20ESP32%20Chip%20Revision%20v3.0%20-%20V2.0%20EN.pdf): so an attacker can read out the private key on one device, and then use that private key to create updates for other devices that share the same keys.

Secure boot and pre-encrypted OTA are indeed two different things, so I don't think it hurts to link to secure boot in the README of pre-encrypted OTA.

2024-02-28 03:15 UTC, mahavirj requested changes

2024-02-28 03:15 UTC, mahavirj commented on examples/system/ota/pre_encrypted_ota/README.md
> +
```suggestion
> [!CAUTION]
> Using the Pre-encrypted Binary OTA provides confidentiality of the firmware, but it does not ensure authenticity of the firmware. For ensuring that the firmware is coming from trusted source, please consider enabling secure boot feature along with the Pre-encrypted binary OTA. Please refer to security guide in the ESP-IDF docs for more details.

```

2024-02-29 04:30 UTC, mahavirj commented
Changes, LGTM!

@redfast00 Could you please squash the commits?

2024-02-29 10:41 UTC, redfast00 commented
@mahavirj done!

2024-03-01 14:16 UTC, mahavirj approved these changes

2024-03-01 14:16 UTC, mahavirj commented
sha=836516b4099deab22e9938d3660943884feef129

2024-03-06 03:49 UTC, merged