feat(fatfs): add Kconfig settings for FF_USE_STRFUNC
espressif/esp-idf pull request #13352
Opened 2024-03-11 00:19 UTC by KJ7LNW

Legacy fatfs code being ported to ESP-IDF may use `f_gets()`, `f_puts()`, `f_putc()`, and `f_printf()` calls, but the define `FF_USE_STRFUNC` is set to 0 without Kconfig options to enable it.

This commit retains the existing default behavior of `FF_USE_STRFUNC=0` and adds Kconfig settings so users can configure `FF_USE_STRFUNC` and the related `FF_PRINT_LLI`, `FF_PRINT_FLOAT`, and `FF_STRF_ENCODE` if needed.

Closes: https://github.com/espressif/esp-idf/issues/13350

(This PR replaces #13351 which had an invalid branch name due to capital letters.)

2024-03-11 00:51 UTC, Alvin1Zhang commented
Thanks for contribution.

2024-03-20 10:01 UTC, haberturdeur commented
Hi, thank you for contributing!

2024-03-20 12:49 UTC, haberturdeur requested changes

2024-03-20 12:54 UTC, haberturdeur requested changes

2024-03-20 12:57 UTC, haberturdeur requested changes

2024-03-20 12:57 UTC, haberturdeur commented on components/fatfs/Kconfig
> +        prompt "Enable string functions, f_gets(), f_putc(), f_puts() and f_printf()"
Please add something along the lines of:
"These are specialized alternatives to stdio functions for working directly with FATFS without VFS."

2024-04-08 21:38 UTC, KJ7LNW commented
@haberturdeur, updated and force pushed.  Please double-check that this is what you needed.

2024-04-09 11:43 UTC, haberturdeur commented
LGTM!

2024-04-09 11:44 UTC, haberturdeur approved these changes

2024-05-17 18:46 UTC, merged