fix: Allocate HTTP header space for async httpd_req_t objects
espressif/esp-idf pull request #13462
Opened 2024-03-25 03:14 UTC by tmiw

This resolves bug #13430 by allocating a new copy of resp_hdrs when calling httpd_req_async_handler_begin(), thus preventing invalid access to memory from async tasks.

2024-03-25 03:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/espressif/esp-idf?pullRequest=13462) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/espressif/esp-idf?pullRequest=13462) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/espressif/esp-idf?pullRequest=13462) it.</sub>

2024-03-26 09:27 UTC, mahavirj requested changes

2024-03-26 09:27 UTC, mahavirj commented on components/esp_http_server/src/httpd_txrx.c
> +    struct httpd_req_aux* asyncAux = (struct httpd_req_aux*)async->aux;
```suggestion
    struct httpd_req_aux *async_aux = (struct httpd_req_aux *) async->aux;
```

2024-03-26 09:27 UTC, mahavirj commented on components/esp_http_server/src/httpd_txrx.c
> +    struct httpd_req_aux* stdAux = (struct httpd_req_aux*)r->aux;
```suggestion
    struct httpd_req_aux *r_aux = (struct httpd_req_aux *) r->aux;
```

2024-03-26 09:27 UTC, mahavirj commented on components/esp_http_server/src/httpd_txrx.c
> +    memcpy(asyncAux->resp_hdrs, stdAux->resp_hdrs, hd->config.max_resp_headers * sizeof(struct resp_hdr));
```suggestion
    memcpy(async_aux->resp_hdrs, r_aux->resp_hdrs, hd->config.max_resp_headers * sizeof(struct resp_hdr));
```

2024-03-26 09:28 UTC, mahavirj commented
Some minor comments, otherwise LGTM!

2024-03-26 15:36 UTC, tmiw commented
> Some minor comments, otherwise LGTM!

Thanks for the feedback! I just pushed some changes to address the formatting/naming comments you had. Let me know if you end up seeing anything else.

2024-03-27 05:58 UTC, mahavirj commented
@tmiw Can you please squash the commits?

2024-03-27 07:51 UTC, tmiw commented
> @tmiw Can you please squash the commits?

Done.

2024-03-27 08:08 UTC, mahavirj commented
sha=f799e9990952847be9d91b2051356fc8f2879676

2024-04-23 16:18 UTC, merged