Document additional errs returned by esp_ota_write
espressif/esp-idf pull request #13764
Opened 2024-05-08 11:07 UTC by lucic71

Otherwise, as in the case of esp_partition_write, we can say: "or one of error codes from lower-level partitions driver".

2024-05-10 04:09 UTC, mahavirj approved these changes

2024-05-10 04:09 UTC, mahavirj commented
sha=ea407fb82ec75a2e666713607e8892f0ffa91556

2024-05-10 05:47 UTC, hmalpani requested changes
Hello @lucic71 
Thanks for updating the documentation. Just one comment otherwise LGTM. Can you please update the PR?
Thanks!

2024-05-10 05:47 UTC, hmalpani commented on components/app_update/include/esp_ota_ops.h
> + *    - ESP_ERR_NOT_ALLOWED: if partition is read-only
`esp_ota_write()` will never return `ESP_ERR_NOT_ALLOWED` as the partitions of subtype `app` are never read-only. For reference: https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-guides/partition-tables.html#flags. I think we can remove this.

I think we can just add the change below as a placeholder for other flash related error codes:
```suggestion
 *    - or one of error codes from lower-level flash driver.
```

2024-05-10 08:26 UTC, hmalpani commented
Hello @lucic71 
Thanks for adding the suggested changes. Can you please squash the commits?

2024-05-10 09:43 UTC, lucic71 commented
Sure, I can to that, @hmalpani.

2024-05-10 10:19 UTC, hmalpani commented
sha=6a8d3af89b9e2f056a48bb5a5fbee6f4ab9c6021

2024-05-16 04:26 UTC, mahavirj commented
Fixed by 37d9a3c183cc1900e797fac8b0dcbe8043ff54ae

2024-05-16 04:26 UTC, closed without merging