python3.12 support: remove distutils use
espressif/esp-idf pull request #14402
Opened 2024-08-19 17:20 UTC by nim65s

Hi,

In python 3.12, the `distutils` module was removed from the standard library.
Here are simple ways to avoid it.

ref. https://docs.python.org/3/whatsnew/3.12.html#distutils

2024-08-19 17:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/espressif/esp-idf?pullRequest=14402) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/espressif/esp-idf?pullRequest=14402) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/espressif/esp-idf?pullRequest=14402) it.</sub>

2024-08-20 12:50 UTC, peterdragun requested changes
Hi @nim65s, thank you for your contribution. Please take a look at the failing pre-commit ci. There are some changes requested like reordering imports. You can check how to install these hooks locally in [Contributions Guide](https://docs.espressif.com/projects/esp-idf/en/stable/esp32/contribute/install-pre-commit-hook.html)

2024-08-20 12:50 UTC, peterdragun commented on tools/mass_mfg/mfg_gen.py
> +from shutil import Path
I believe you wanted to import Path from `pathlib` instead of `shutil`

2024-09-04 16:14 UTC, nim65s commented
thanks @peterdragun, I think this is better now.

2024-09-14 23:34 UTC, merged