[mdns] fix wrong mdns source address
espressif/esp-idf pull request #6055
Opened 2020-11-02 06:43 UTC by gjc13

The struct definition of ip6_addr_t in lwip and esp_ip6_addr_t
differs since zone is not enabled in lwip. Using `memcpy` to copy the
address will cause wrong source address. Copy the entries manually
instead.

2020-11-02 06:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/espressif/esp-idf?pullRequest=6055) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/espressif/esp-idf?pullRequest=6055) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/espressif/esp-idf?pullRequest=6055) it.</sub>

2020-11-02 07:26 UTC, Alvin1Zhang commented
Thanks for your contribution.

2020-11-02 17:05 UTC, david-cermak commented
Hi @gjc13 

Yes, these two `struct` definitions differ, but the scope_id is enabled in IDF, assuming it's not forced into lwip component otherwise. In that case it might be possible the addr-type would not be copied correctly, is this what you're trying to address? if so, i'd suggest copying `u_addr` field and assigning the `type` manually.

2020-11-02 17:06 UTC, david-cermak commented on components/mdns/mdns_networking.c
> +        if (raddr->type == IPADDR_TYPE_V4) {
Is this condition correct? seems to me we would like to copy the IPv4 address if the type is `IPADDR_TYPE_V4`

2020-11-02 17:08 UTC, david-cermak requested changes
Please elaborate on the condition or/and think of an easier way to address the issue, such as
``` c
memcpy(packet->src.u_addr, raddr->u_addr, sizeof(raddr->u_addr));
packet->src.type = raddr->type;
```

2020-11-05 10:49 UTC, gjc13 commented
> Please elaborate on the condition or/and think of an easier way to address the issue, such as
> 
> ```c
> memcpy(packet->src.u_addr, raddr->u_addr, sizeof(raddr->u_addr));
> packet->src.type = raddr->type;
> ```

Updated

2020-11-06 07:36 UTC, david-cermak commented
@gjc13 Thanks for the update, this LGTM in general. Could you please also click trough the CLA agreement?
Just two nitpicks which could be applied internally:
* copy from the address of the union
* copy `sizeof()` of the union, the `ip6` size is the same but i'd just find it more readable
``` c
memcpy(&packet->src.u_addr, &raddr->u_addr, sizeof(raddr->u_addr));
```

2020-11-06 09:27 UTC, closed without merging