Allow KConfig to set LWIP checksum check state
espressif/esp-idf pull request #6187
Opened 2020-12-01 00:37 UTC by ryankurte

for some reason (?!) the ESP LWIP configuration defaults to disabling checksum validation for IP, UDP, and ICMP packets. this PR adds KConfig options to configure LWIP checksums and passes these through to the platform config.

the `Checksums` submenu is there because while there are `ICMP` and `UDP` menus that these could be nested under, there is not one for `IP`.

cc. @webworxshop

2020-12-01 01:37 UTC, Alvin1Zhang commented
Thanks for your contribution.

2020-12-01 15:54 UTC, david-cermak reviewed
Thanks for posting this useful update! Please see my comments to the changes.

2020-12-01 15:54 UTC, david-cermak commented on components/lwip/Kconfig
> +        range 0 1
We usually prefer boolean type for these enable/disable options.

2020-12-01 15:54 UTC, david-cermak commented on components/lwip/Kconfig
> +        default 0
Current master has the `ICMP` checksums turned `ON` if i'm not mistaken, so suggest keeping the compatibility.

2020-12-06 20:47 UTC, david-cermak commented
Thanks for the update. I'm sorry, didn't answer the question:

> for some reason (?!) the ESP LWIP configuration defaults to disabling checksum validation

This configuration is used in esp-lwip from its initial version. TBH not sure what was the primary reason, but I think this makes some sense, since:
* IDF developers always place importance on performance and network thoughput and UDP/IP checksum validation has an impact on the UDP and TCP bandwidth (see [iperf](https://github.com/espressif/esp-idf/tree/master/examples/wifi/iperf) example) unlike the ICMP checksum (which defaults to *ON*)
* Checksums on IP and UDP layers are useful, but since the frame check sequence is validated on lower layers we have certain confidence about the packets and the upper layer protocols being valid.

2020-12-06 20:54 UTC, david-cermak requested changes
I think this change would break our internal throughput tests (unlike the previous version). We have to maintain backward compatibility in the default settings.

2020-12-06 20:54 UTC, david-cermak commented on components/lwip/Kconfig
> +        default y
This should default to "no", as mentioned before.

2020-12-06 20:54 UTC, david-cermak commented on components/lwip/Kconfig
> +        default y
Same here.

2020-12-08 07:10 UTC, david-cermak approved these changes
LGTM!

2021-01-06 01:19 UTC, Alvin1Zhang commented
Thanks for contribution, changes merged with https://github.com/espressif/esp-idf/commit/5d91a27a1eed9f3b4602e0874b7b216750f6cdd9

2021-01-06 01:19 UTC, closed without merging