Fixed esp_core_dump_image_erase() for flash encryption with 16byte long write buffers
espressif/esp-idf pull request #6949
Opened 2021-04-27 13:22 UTC by 0xFEEDC0DE64

esp_partition_write() kept failing in esp_core_dump_image_erase() when I enabled flash encryption, as the write function then requires multiple of 16 byte long write buffers.

I changed the erase method so it always writes 16 bytes and the blank coredump size at the beginning.

Also I added a compile time static assert to make sure the struct has a valid size.

2021-05-06 02:36 UTC, Alvin1Zhang commented
@0xFEEDC0DE64 Thanks for your contribution.

2021-05-31 16:04 UTC, 0xFEEDC0DE64 commented
Is this fix already merged? or is there anything I can do to help?

2021-06-01 14:45 UTC, o-marshmallow commented
Hello @0xFEEDC0DE64,

Sorry for the delay of response, thank you for your contribution once again :smile: !
I am going to handle this

2021-06-01 14:55 UTC, o-marshmallow requested changes
I just added few comments to simplify what you did, please check them

2021-06-01 14:55 UTC, o-marshmallow commented on components/espcoredump/src/core_dump_flash.c
> +    // helper to create (multiple of) 16 byte long write buffers
There is a simpler way to do that I would prefer, it's to add at the beginning of this function the following snippet:
```
/* If flash is encrypted, we can only write blocks of 16 bytes. */
uint32_t helper[4] = { BLANK_COREDUMP_SIZE };
```
You can add the static assert right after (same as now, `sizeof(helper)` will return 16).

2021-06-01 14:55 UTC, o-marshmallow commented on components/espcoredump/src/core_dump_flash.c
> +    memset(&helper.buf, '\0', sizeof(helper.buf));
If you follow my comment above, no need to `memset` the memory

2021-06-01 14:55 UTC, o-marshmallow commented on components/espcoredump/src/core_dump_flash.c
> +#include "esp_core_dump.h"
Was these includes strictly required?  `_Static_assert` can be used without them

2021-07-16 10:30 UTC, closed without merging