Update vscode-setup.rst
espressif/esp-idf pull request #8437
Opened 2022-02-19 19:55 UTC by andypiper

Improved formatting and grammar, fixed links so that they render correctly

2022-02-19 19:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/espressif/esp-idf?pullRequest=8437) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/espressif/esp-idf?pullRequest=8437) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/espressif/esp-idf?pullRequest=8437) it.</sub>

2022-02-20 02:37 UTC, krzychb requested changes
Hi @andypiper,
I left one small comment. The updates are great. 
Thank you for your contribution!

2022-02-20 02:37 UTC, krzychb commented on docs/en/get-started/vscode-setup.rst
> +If you face an issue with certain feature of VS Code or VS Code in general we recommend you ask your question in the `forum <http://esp32.com/viewforum.php?f=40>`_, or open a `GithHb Issue <https://g
```suggestion
If you face an issue with certain feature of VS Code or VS Code in general we recommend you ask your question in the `forum <http://esp32.com/viewforum.php?f=40>`_, or open a `GitHub Issue <https://github.com/espressif/vscode-esp-idf-extension/issues/new/choose>`_ for our dev teams to review.
```

2022-02-21 11:34 UTC, pedrominatel reviewed
Please take a look @andypiper.

2022-02-21 11:34 UTC, pedrominatel commented on docs/en/get-started/vscode-setup.rst
> +* `Rainmaker Cloud <https://rainmaker.espressif.com/>`_, we have inbuilt Rainmaker Cloud support where you can edit/read the state of your connected IoT devices easily.
and

```
* **Rainmaker Cloud**, we have inbuilt Rainmaker Cloud support where you can edit/read the state of your connected IoT devices easily. For more information see this `page <https://rainmaker.espressif.com/>`_
``

2022-02-21 11:34 UTC, pedrominatel commented
Hi @andypiper, thanks for the valuable contribution!

I see some issues on building this change using our docs-build. Please see my suggestions.

Thanks!

2022-02-21 14:08 UTC, andypiper commented
Thanks for the review and apologies for those errors, I like the suggestions as better ways to get uniform formatting in the list here. I've rechecked the links this time.

2022-02-22 08:46 UTC, pedrominatel commented
LGTM! Thanks @andypiper

2022-02-24 08:21 UTC, krzychb commented
I have taken this PR into the internal queue for merging.
Thank you @andypiper!

2022-03-11 10:54 UTC, krzychb commented
Merged in https://github.com/espressif/esp-idf/commit/6249b3d6718372c12ae96dd288181cd058abeca4

2022-03-11 10:54 UTC, closed without merging