Move xSemaphoreGive out of configASSERT
espressif/esp-idf pull request #9497
Opened 2022-08-04 14:42 UTC by tgotic

xSemaphoreGive won't be executed in configASSERT and semaphore will stay locked if NDEBUG (idf v5) or CONFIG_FREERTOS_ASSERT_DISABLE (idf v3, v4) are defined.

2022-08-04 15:12 UTC, igrr requested changes
Thank you for noticing the bug and submitting the fix! Have left just one request about making the code more readable.

2022-08-04 15:12 UTC, igrr commented on components/esp_ringbuf/ringbuf.c
> +        xHoldSemaphore = xSemaphoreGive(rbGET_RX_SEM_HANDLE(pxRingbuffer));
Would you consider changing this assignment to some new variable? Repurposing the xHoldSemaphore variable for the return code looks a bit odd here.

(same in the case below)

2022-08-08 01:31 UTC, Alvin1Zhang commented
Thanks for your contribution.

2022-08-11 16:01 UTC, Dazza0 commented
LGTM

2022-08-11 16:03 UTC, Dazza0 commented
sha=9762c9ae1c2878a554d5ed531019206951b95e8f

2022-08-11 16:04 UTC, Dazza0 approved these changes

2022-08-16 07:53 UTC, merged